### ISSUE TITLE
There seems to be NO support for batch in v2.3.0

### ISSUE THREAD

**Issue by bwillenbring** [shotgunsoftware/shotgun-nodejs#2]
Currently, I don't think this package has a method that lines up with the [batch method – described here](https://developer.shotgunsoftware.com/rest-api/#batch-execute-requests). It would be a great addition.

### Use cases
- Creating several entities in a single array of requests, rather than one-by-one
- Sending a mix of create and update requests in a single array of requests 

**Maybe something like**
```javascript
shotgun.entityBatch({ requests });
```
**Where `requests` is your typical array of requests like...**
```javascript
// Don't forget about the options param in create requests! 
[
    {
      "request_type": "create",
      "entity": "Asset",
      "data": {
        "code": "new asset"
      },
      "options": {
        "fields": [
          "code"
        ]
      }
    }
  ]
```

**Comment by souphan-adsk** [comment]
Addressed in #5.
